[pytest]

python_files = test_*.py
python_functions = test_*

markers =
    smoke: Critical smoke tests
    sanity: Basic functionality validation
    regression: Full regression coverage

    device: Device related tests
    device_info: Device information validation
    installation: App installation validation

    load: App launch and loading tests
    display: Home page display verification

    app_info: Package, activity, version and state checks
    title: Page title validation
    menu: Menu item validation

    navigation: Navigation flow tests

    restart: App restart tests
    background: Backgrounding app tests
    lifecycle: App lifecycle management tests

    notification: Notification panel tests
    open_notifications: Open notification shade
    full_notifications_open: Expand notification panel
    full_notifications_close: Collapse notification panel

addopts =
    -v
    --html=Reports/html/report.html
    --self-contained-html
    --junitxml=Reports/junit/junit.xml
    --alluredir=Reports/allure-results

log_cli = true
log_cli_level = INFO

log_cli_format = %(asctime)s | %(levelname)s | %(worker)s | %(name)s | %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

console_output_style = progress